### ISSUE TITLE
PHP 8.2 fix

### ISSUE THREAD

**Issue by dleffler** [scssphp/server#11]
Due to some deprecatons in PHP v8.2, Server.php line # 215 needs to be changed to move the $ into the curly braces
````
        $css  = "/* compiled by scssphp $v on $t ({$elapsed}s) */\n\n" . $css;
````
instead of
````
        $css  = "/* compiled by scssphp $v on $t (${elapsed}s) */\n\n" . $css;

**Comment by robocoder** [comment]
Thanks.  Pushed to 905066da4d5a51138e60250cef60d375f6e94d99 and tagged as 1.10.1
