### ISSUE TITLE
State of the project

### ISSUE THREAD

**Issue by stof** [scssphp/server#4]
This project has not seen any recent activity. And it will be impacted by deprecations coming in scssphp 1.5.

This project should either be officially abandoned or be updated for new versions of scssphp.
However, I have absolutely no interest into maintaining this scssphp/server package myself. So I won't do the work of updating it myself.

/cc @robocoder

**Comment by robocoder** [comment]
Server was originally a part of leafo/scssphp. This repo was created to separate it from the library.

**Comment by stof** [comment]
should we mark it as abandoned and archive the repo ? or are you maintaining it ?

**Comment by robocoder** [comment]
I'll update the repo as long as there's interest. I just tagged a release to roll-up the recent PRs.
